// Datos del portafolio — extraídos del spec de diseño (Portafolio.dc.html).
// Las rutas de imagen (logos/..., projects/.../...) apuntan a los assets
// pesados que aún no se han subido. Ver ASSETS.md para dónde colocarlos.

const CLIENTS = [
  { id: 'c1', name: 'Bella Design Painting', image: 'logos/bella.png', category: 'Branding, sitio web & redes sociales', website: 'www.belladesignpainting.com', summary: 'Negocio de mantenimiento y pintura doméstica en El Paso, Texas. Diseño de identidad de marca, remodelación de sitio web, aplicaciones de marca y apertura de redes sociales.', projects: [
    { title: 'Logotipo y paleta de color', type: 'Branding', image: 'projects/bella/logo-color.jpg' },
    { title: 'Tarjetas de presentación', type: 'Papelería', image: 'projects/bella/tarjetas.jpg' },
    { title: 'Aplicaciones de marca', type: 'Branding', image: 'projects/bella/aplicaciones-1.jpg' },
    { title: 'Mercancía de marca', type: 'Branding', image: 'projects/bella/aplicaciones-2.jpg' },
    { title: 'Uniformes y gorras', type: 'Branding', image: 'projects/bella/aplicaciones-3.jpg' },
    { title: 'Página de Facebook', type: 'Redes sociales', image: 'projects/bella/facebook.jpg' },
  ]},
  { id: 'c2', name: 'Empire Fitness Center', image: 'logos/empire-fitness.jpg', category: 'Manejo de redes sociales & impresos', summary: 'Gimnasio con tres sucursales en Ciudad Obregón, Sonora. Diseño y manejo de contenido para redes sociales (posts, historias y anuncios) y material impreso: flyers, cupones y promociones.', projects: [
    { title: 'Página de Facebook', type: 'Redes sociales', image: 'projects/empire/facebook.jpg' },
    { title: 'Feed de Instagram', type: 'Redes sociales', image: 'projects/empire/instagram-mockup.jpg' },
    { title: 'Flyers y cupones de promoción', type: 'Impresos', image: 'projects/empire/impresos.jpg' },
    { title: 'Posts de campaña', type: 'Redes sociales', image: 'projects/empire/post-1.jpg' },
    { title: 'Posts de promoción y horarios', type: 'Redes sociales', image: 'projects/empire/post-2.jpg' },
    { title: 'Contenido motivacional', type: 'Redes sociales', image: 'projects/empire/post-3.jpg' },
    { title: 'Vacantes y avisos', type: 'Redes sociales', image: 'projects/empire/post-4.jpg' },
    { title: 'Posts informativos', type: 'Redes sociales', image: 'projects/empire/post-5.jpg' },
    { title: 'Publicidad de productos', type: 'Redes sociales', image: 'projects/empire/post-6.jpg' },
  ]},
  { id: 'c3', name: 'CEIAC', image: 'logos/ceiac.png', category: 'Diseño UI/UX accesible', summary: 'Plataforma de cursos en línea para personas con déficit visual, diseñada en Adobe XD. Proyecto realizado mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Panel de inicio', type: 'UI/UX', image: 'projects/ceiac/dashboard.png' },
    { title: 'Inicio de sesión', type: 'UI/UX', image: 'projects/ceiac/login.png' },
    { title: 'Vista de tema', type: 'UI/UX', image: 'projects/ceiac/tema.png' },
    { title: 'Actividades pendientes', type: 'UI/UX', image: 'projects/ceiac/actividades.png' },
    { title: 'Detalle de curso', type: 'UI/UX', image: 'projects/ceiac/curso.png' },
  ]},
  { id: 'c4', name: 'Verbum Comunicación', image: 'logos/verbum.jpg', category: 'Branding & sitio web', summary: 'Agencia de comunicación. Diseño de identidad de marca, tarjetas de presentación y sitio web tipo one page.', projects: [
    { title: 'Logotipo y paleta de color', type: 'Branding', image: 'projects/verbum/logo-color.jpg' },
    { title: 'Tarjetas de presentación', type: 'Papelería', image: 'projects/verbum/tarjetas.jpg' },
    { title: 'Sitio web one page', type: 'Diseño web', image: 'projects/verbum/sitio-web.jpg' },
  ]},
  { id: 'c5', name: 'Fumi Servicios del Noroeste', image: 'logos/fumiservicios.jpg', category: 'Branding, impresos & redes sociales', summary: 'Empresa de fumigación y mantenimiento en Guaymas, Sonora. Diseño de identidad de marca, tarjetas de presentación, lonas, sellos y manejo de redes sociales.', projects: [
    { title: 'Logotipo y paleta de color', type: 'Branding', image: 'projects/fumiservicios/logo-color.jpg' },
    { title: 'Tarjetas de presentación', type: 'Papelería', image: 'projects/fumiservicios/tarjetas.jpg' },
    { title: 'Sello de marca', type: 'Branding', image: 'projects/fumiservicios/sello.png' },
    { title: 'Lona publicitaria', type: 'Impresos', image: 'projects/fumiservicios/lona.png' },
    { title: 'Página de Facebook', type: 'Redes sociales', image: 'projects/fumiservicios/facebook.jpg' },
    { title: 'Publicidad en Instagram', type: 'Redes sociales', image: 'projects/fumiservicios/instagram.jpg' },
    { title: 'Control de roedores', type: 'Redes sociales', image: 'projects/fumiservicios/post-roedores.jpg' },
    { title: 'Termita subterránea', type: 'Redes sociales', image: 'projects/fumiservicios/post-termita.jpg' },
    { title: 'Cobertura en Sonora', type: 'Redes sociales', image: 'projects/fumiservicios/post-sonora.jpg' },
    { title: 'Calendario de plagas', type: 'Redes sociales', image: 'projects/fumiservicios/post-calendario.jpg' },
  ]},
  { id: 'c6', name: 'FS Autolavado', image: 'logos/fs-autolavado.jpg', category: 'Branding, redes sociales & impresos', summary: 'Autolavado en Guaymas, Sonora. Diseño de identidad de marca, manejo de redes sociales e impresos para el local.', projects: [
    { title: 'Logotipo y paleta de color', type: 'Branding', image: 'projects/fs-autolavado/logo-color.jpg' },
    { title: 'Página de Facebook', type: 'Redes sociales', image: 'projects/fs-autolavado/facebook.jpg' },
    { title: 'Publicidad en Instagram', type: 'Redes sociales', image: 'projects/fs-autolavado/instagram.jpg' },
    { title: 'Servicio de pulido', type: 'Redes sociales', image: 'projects/fs-autolavado/post-pulido.jpg' },
    { title: 'Limpieza de motor', type: 'Redes sociales', image: 'projects/fs-autolavado/post-motor.jpg' },
    { title: 'Lavado a detalle', type: 'Redes sociales', image: 'projects/fs-autolavado/post-detalle.jpg' },
    { title: 'Lona publicitaria', type: 'Impresos', image: 'projects/fs-autolavado/lona.jpg' },
    { title: 'Bandera de local', type: 'Impresos', image: 'projects/fs-autolavado/bandera.jpg' },
    { title: 'Croquis de ubicación', type: 'Impresos', image: 'projects/fs-autolavado/croquis.jpg' },
  ]},
  { id: 'c7', name: 'Velvet Sex Shop', image: 'logos/velvet.jpg', category: 'Branding & redes sociales', ageRestricted: true, summary: 'Sex shop en Guaymas, Sonora. Diseño de identidad de marca y manejo de redes sociales.', projects: [
    { title: 'Logotipo y paleta de color', type: 'Branding', image: 'projects/velvet/logo-color.jpg' },
    { title: 'Página de Facebook', type: 'Redes sociales', image: 'projects/velvet/facebook.jpg' },
    { title: 'Publicidad en Instagram', type: 'Redes sociales', image: 'projects/velvet/instagram.jpg' },
    { title: 'Campaña "Free your desires"', type: 'Redes sociales', image: 'projects/velvet/post-desires.jpg' },
    { title: 'Campo de juego', type: 'Redes sociales', image: 'projects/velvet/post-campo.jpg' },
    { title: 'Producto de silicón', type: 'Redes sociales', image: 'projects/velvet/post-silicon.jpg' },
    { title: 'Día del orgasmo femenino', type: 'Redes sociales', image: 'projects/velvet/post-orgasmo.jpg' },
  ]},
  { id: 'c8', name: 'CDR — Centro Diagnóstico del Rincón', image: 'logos/cdr.jpg', category: 'Propuesta de sitio web', summary: 'Centro de diagnóstico médico e imagenología. Propuesta de sitio web en Adobe XD, realizada mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Página de inicio y nosotros', type: 'Diseño web', image: 'projects/cdr/hero-nosotros.jpg' },
    { title: 'Equipo médico y redes sociales', type: 'Diseño web', image: 'projects/cdr/equipo-redes.jpg' },
  ]},
  { id: 'c9', name: 'Rotary Club San Carlos', image: 'logos/rotario.jpg', category: 'Digitalización de logo & propuesta de banner', summary: 'Rotary Club San Carlos, Sonora. Proyecto por cuenta propia: digitalización de logotipo, propuesta de banner para redes e iconos institucionales.', projects: [
    { title: 'Logotipo digitalizado', type: 'Branding', image: 'projects/rotary/logo.jpg' },
    { title: 'Banner para redes sociales', type: 'Redes sociales', image: 'projects/rotary/banner.jpg' },
    { title: 'Icono — Salud', type: 'Iconografía', image: 'projects/rotary/icono-salud.png' },
    { title: 'Icono — Educación', type: 'Iconografía', image: 'projects/rotary/icono-educacion.png' },
    { title: 'Icono — Medio ambiente', type: 'Iconografía', image: 'projects/rotary/icono-ambiental.png' },
  ]},
  { id: 'c10', name: 'CY Beauty', image: 'logos/cy-beauty.jpg', category: 'Branding & propuesta de sitio web', summary: 'Marca de joyería. Identidad de marca y propuesta de sitio web en Adobe XD, realizados mientras trabajaba en TICA Solutions (2021-2022), Mazatlán.', projects: [
    { title: 'Logotipo y paleta de color', type: 'Branding', image: 'projects/cy-beauty/logo-color.jpg' },
    { title: 'Página de inicio', type: 'Diseño web', image: 'projects/cy-beauty/home.jpg' },
    { title: 'Página "Nosotros"', type: 'Diseño web', image: 'projects/cy-beauty/nosotros.jpg' },
    { title: 'Página de producto', type: 'Diseño web', image: 'projects/cy-beauty/producto.jpg' },
    { title: 'Página de tienda', type: 'Diseño web', image: 'projects/cy-beauty/tienda.jpg' },
    { title: 'Banner promocional', type: 'Diseño web', image: 'projects/cy-beauty/banner.jpg' },
    { title: 'Página de contacto', type: 'Diseño web', image: 'projects/cy-beauty/contacto.jpg' },
    { title: 'Página de blog', type: 'Diseño web', image: 'projects/cy-beauty/blog.jpg' },
  ]},
  { id: 'c11', name: 'El Julio Garabato', image: 'logos/julio-garabato.jpg', category: 'Actualización de logo & redes sociales', summary: 'Frutería local. Actualización de logotipo y manejo de redes sociales, realizado mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Actualización de logotipo y paleta', type: 'Branding', image: 'projects/julio-garabato/logo-color.jpg' },
    { title: 'Página de Facebook', type: 'Redes sociales', image: 'projects/julio-garabato/facebook.jpg' },
    { title: 'Feed de Instagram', type: 'Redes sociales', image: 'projects/julio-garabato/instagram.jpg' },
    { title: 'Portada de campaña', type: 'Redes sociales', image: 'projects/julio-garabato/portada.jpg' },
    { title: 'Mejores precios y calidad', type: 'Redes sociales', image: 'projects/julio-garabato/post-mejores-precios.jpg' },
    { title: 'Promoción de fresa', type: 'Redes sociales', image: 'projects/julio-garabato/post-fresa.jpg' },
    { title: 'Promoción de naranja', type: 'Redes sociales', image: 'projects/julio-garabato/post-naranja.jpg' },
    { title: 'Tips y trucos', type: 'Redes sociales', image: 'projects/julio-garabato/post-trucos.jpg' },
  ]},
  { id: 'c12', name: 'Maz Uniform', image: 'logos/maz-uniform.jpg', category: 'Rediseño de logo, redes sociales & banners', summary: 'Línea de uniformes médicos. Rediseño de logotipo, manejo de redes sociales y actualización de banners web, realizado mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Rediseño de logotipo', type: 'Branding', image: 'projects/maz-uniform/logo-old-new.jpg' },
    { title: 'Logotipo y variantes de color', type: 'Branding', image: 'projects/maz-uniform/logo-color.jpg' },
    { title: 'Página de Facebook', type: 'Redes sociales', image: 'projects/maz-uniform/facebook.jpg' },
    { title: 'Feed de Instagram', type: 'Redes sociales', image: 'projects/maz-uniform/instagram.jpg' },
    { title: 'Presentación de modelos', type: 'Redes sociales', image: 'projects/maz-uniform/post-modelos.jpg' },
    { title: 'Jumpsuit Harmony', type: 'Redes sociales', image: 'projects/maz-uniform/post-jumpsuit.jpg' },
    { title: 'Nuevos modelos', type: 'Redes sociales', image: 'projects/maz-uniform/post-nuevos-modelos.jpg' },
    { title: 'Banner navideño', type: 'Banner web', image: 'projects/maz-uniform/banner-navidad.jpg' },
    { title: 'Banner Buen Fin', type: 'Banner web', image: 'projects/maz-uniform/banner-buen-fin.jpg' },
    { title: 'Banner mes del amor y la amistad', type: 'Banner web', image: 'projects/maz-uniform/banner-amor.jpg' },
  ]},
  { id: 'c13', name: 'Punto49', image: 'logos/punto49.jpg', category: 'Branding, stickers, iconografía & redes sociales', summary: 'Estudio gráfico. Creación de marca, identidad, stickers, iconografía y manejo de redes sociales.', projects: [
    { title: 'Logotipo circular a color', type: 'Branding', image: 'projects/punto49/logo-circular.png' },
    { title: 'Variante de color', type: 'Branding', image: 'projects/punto49/logo-color.png' },
    { title: 'Logotipo horizontal', type: 'Branding', image: 'projects/punto49/logo-horizontal.png' },
    { title: 'Isotipo', type: 'Branding', image: 'projects/punto49/isotipo.png' },
    { title: 'Stickers de marca', type: 'Papelería', image: 'projects/punto49/stickers-negro.png' },
    { title: 'Tarjetas de presentación', type: 'Papelería', image: 'projects/punto49/tarjetas.png' },
    { title: 'Tarjeta — reverso', type: 'Papelería', image: 'projects/punto49/tarjeta-reverso.png' },
    { title: 'Manejo de redes sociales', type: 'Redes sociales', image: 'projects/punto49/post-redes.jpg' },
    { title: 'Fotografía de producto', type: 'Redes sociales', image: 'projects/punto49/post-fotografia.jpg' },
    { title: 'Expertos en marketing digital', type: 'Redes sociales', image: 'projects/punto49/post-marketing.jpg' },
    { title: 'Tu marca cerca de tus clientes', type: 'Redes sociales', image: 'projects/punto49/post-tumarca.jpg' },
    { title: 'Diseño de páginas web', type: 'Redes sociales', image: 'projects/punto49/post-web.jpg' },
    { title: 'Estudio gráfico', type: 'Redes sociales', image: 'projects/punto49/post-estudio.jpg' },
    { title: 'Paquete de redes — Nivel 1', type: 'Servicios', image: 'projects/punto49/paq-redes-1.png' },
    { title: 'Paquete de redes — Nivel 2', type: 'Servicios', image: 'projects/punto49/paq-redes-2.png' },
    { title: 'Paquete de redes — Nivel 3', type: 'Servicios', image: 'projects/punto49/paq-redes-3.png' },
  ]},
  { id: 'c14', name: 'TICA Solutions', image: 'logos/tica.jpg', category: 'Manejo de redes sociales', summary: 'Empresa de soluciones tecnológicas y desarrollo web (donde trabajé). Manejo de redes sociales de la marca directamente.', projects: [
    { title: 'Promoción — sitio web responsive', type: 'Redes sociales', image: 'projects/tica/promo-web-responsive.jpg' },
    { title: 'Promoción — SEO', type: 'Redes sociales', image: 'projects/tica/promo-seo.png' },
    { title: 'Portada de Facebook', type: 'Redes sociales', image: 'projects/tica/facebook-portada.jpg' },
    { title: 'Feed de Instagram', type: 'Redes sociales', image: 'projects/tica/instagram.jpg' },
    { title: 'Manejo de redes sociales', type: 'Redes sociales', image: 'projects/tica/redes-sociales.jpg' },
    { title: 'Forma parte de la web', type: 'Redes sociales', image: 'projects/tica/forma-parte-web.jpg' },
    { title: 'Promoción — eCommerce', type: 'Redes sociales', image: 'projects/tica/ecommerce.jpg' },
    { title: 'Página web, hosting y dominio', type: 'Redes sociales', image: 'projects/tica/pagina-web-hosting.jpg' },
    { title: 'Venta en redes sociales', type: 'Redes sociales', image: 'projects/tica/venta-redes.jpg' },
    { title: 'Publicación de año nuevo', type: 'Redes sociales', image: 'projects/tica/ano-nuevo.jpg' },
  ]},
  { id: 'c15', name: 'Planning Solutions', image: 'logos/planning-solutions.png', category: 'Diseño web', summary: 'Central de medios y agencia de investigación de mercado. Diseño de sitio web, realizado mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Página de inicio', type: 'Diseño web', image: 'projects/planning/home.jpg' },
    { title: 'Somos expertos en medios', type: 'Diseño web', image: 'projects/planning/expertos-medios.jpg' },
    { title: 'Valores: innovación, trayectoria, profesionalismo', type: 'Diseño web', image: 'projects/planning/valores.jpg' },
    { title: 'Data Solutions', type: 'Diseño web', image: 'projects/planning/data-solutions.jpg' },
    { title: '¿Qué tipo de estudios realizamos?', type: 'Diseño web', image: 'projects/planning/tipos-estudios.jpg' },
    { title: 'Clientes', type: 'Diseño web', image: 'projects/planning/clientes.jpg' },
    { title: 'Contacto', type: 'Diseño web', image: 'projects/planning/contacto.jpg' },
  ]},
  { id: 'c16', name: 'Lupita López', image: 'logos/lupita-lopez.png', category: 'Diseño web', summary: 'Nutrióloga. Diseño de sitio web y tienda en línea, realizado mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Sitio web — inicio', type: 'Diseño web', image: 'projects/lupita/home-sitio.jpg' },
    { title: 'Tienda en línea — inicio', type: 'Diseño web', image: 'projects/lupita/home-tienda.jpg' },
  ]},
  { id: 'c17', name: 'Grupo Corporativo Clapasa del Norte', image: 'logos/clapasa.png', category: 'Diseño de sitio web', summary: 'Grupo empresarial de servicios de capital humano: promotoría, seguridad y limpieza. Diseño de sitio web, realizado mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Página de inicio', type: 'Diseño web', image: 'projects/clapasa/hero.png' },
    { title: 'Formulario de contacto', type: 'Diseño web', image: 'projects/clapasa/formulario.png' },
    { title: 'Sé parte de nuestro equipo', type: 'Diseño web', image: 'projects/clapasa/equipo.png' },
    { title: 'Áreas de atención', type: 'Diseño web', image: 'projects/clapasa/areas-atencion.png' },
    { title: 'Más de 10 años de experiencia', type: 'Diseño web', image: 'projects/clapasa/experiencia.png' },
  ]},
  { id: 'c18', name: 'Millennium Peluquería & Salón', image: 'logos/millennium.png', category: 'Logotipo & identidad', summary: 'Identidad de marca para salón de belleza.', projects: [
    { title: 'Logotipo', type: 'Branding', placeholder: 'logotipo' },
    { title: 'Señalética de salón', type: 'Ambiental', placeholder: 'foto de interior' },
  ]},
  { id: 'c19', name: 'ImperShop', image: 'logos/impershop.png', category: 'Rotulado, redes & papelería', summary: 'Pinturas e impermeabilizantes en Guaymas. Rotulado vehicular, papelería, fotografía y manejo de redes sociales.', projects: [
    { title: 'Rotulado de van — lateral', type: 'Rotulado', image: 'projects/impershop/rotulo-van-lateral.jpg' },
    { title: 'Rotulado de van — trasera', type: 'Rotulado', image: 'projects/impershop/rotulo-van-trasera.jpg' },
    { title: 'Papelería corporativa', type: 'Papelería', image: 'projects/impershop/papeleria.jpg' },
    { title: 'Sitio web — Nosotros', type: 'Diseño web', image: 'projects/impershop/web-nosotros.jpg' },
    { title: 'Sitio web — Ventajas', type: 'Diseño web', image: 'projects/impershop/web-ventajas.jpg' },
    { title: 'Sitio web — Contacto', type: 'Diseño web', image: 'projects/impershop/web-contacto.jpg' },
    { title: 'Publicidad de producto', type: 'Redes sociales', image: 'projects/impershop/promo-1.jpg' },
    { title: 'Promoción de temporada', type: 'Redes sociales', image: 'projects/impershop/promo-2.jpg' },
  ]},
  { id: 'c20', name: 'Cactus Carpintería de Playa', image: 'logos/cactus.png', category: 'Redes sociales & papelería', summary: 'Carpintería de playa en San Carlos, Guaymas. Manejo de redes sociales y papelería corporativa, realizado durante mi tiempo en Grupo ECO.', projects: [
    { title: 'Papelería corporativa', type: 'Papelería', image: 'projects/cactus/papeleria.jpg' },
    { title: 'Instalaciones y proyectos', type: 'Fotografía', image: 'projects/cactus/instalaciones.jpg' },
    { title: 'Publicaciones para redes', type: 'Redes sociales', image: 'projects/cactus/redes-1.jpg' },
    { title: 'Contenido de campaña', type: 'Redes sociales', image: 'projects/cactus/redes-2.jpg' },
    { title: 'Perfiles Facebook & Instagram', type: 'Redes sociales', image: 'projects/cactus/perfil-fb-ig.jpg' },
  ]},
  { id: 'c21', name: 'Eco Fumigaciones Ecológicas', image: 'logos/eco-fumigaciones.png', category: 'Identidad, redes & rotulado', summary: 'Empresa de fumigación ecológica en Guaymas/Hermosillo. Identidad de marca completa, papelería, rotulado vehicular, señalética, fotografía y manejo de redes sociales.', projects: [
    { title: 'Publicación de redes', type: 'Redes sociales', image: 'projects/ecofumigaciones/redes-1.jpg' },
    { title: 'Inspección de termitas', type: 'Redes sociales', image: 'projects/ecofumigaciones/redes-2.jpg' },
    { title: 'Campaña de prevención', type: 'Redes sociales', image: 'projects/ecofumigaciones/redes-3.jpg' },
    { title: 'Infografía — tipos de termitas', type: 'Redes sociales', image: 'projects/ecofumigaciones/infografia-termitas.jpg' },
    { title: 'Rotulado de van — lateral', type: 'Rotulado', image: 'projects/ecofumigaciones/rotulo-van.jpg' },
    { title: 'Rotulado de van — trasera', type: 'Rotulado', image: 'projects/ecofumigaciones/rotulo-van-trasera.jpg' },
    { title: 'Rotulado de camioneta', type: 'Rotulado', image: 'projects/ecofumigaciones/rotulo-camioneta.jpg' },
    { title: 'Señalética de control de plagas', type: 'Ambiental', image: 'projects/ecofumigaciones/senaletica.jpg' },
    { title: 'Exhibición de productos', type: 'Fotografía', image: 'projects/ecofumigaciones/anaqueles.jpg' },
    { title: 'Tarjetas de presentación', type: 'Papelería', image: 'projects/ecofumigaciones/tarjetas.jpg' },
  ]},
  { id: 'c22', name: 'Stumbaugh and Associates', image: 'logos/stumbaugh.png', category: 'Diseño de eCommerce', summary: 'Proveedor de particiones y accesorios para baños en California. Diseño de eCommerce, realizado mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Página de inicio', type: 'eCommerce', image: 'projects/stumbaugh/homepage.jpg' },
    { title: 'Página de producto', type: 'eCommerce', image: 'projects/stumbaugh/product.jpg' },
    { title: 'Listado de productos', type: 'eCommerce', image: 'projects/stumbaugh/products.jpg' },
    { title: 'Inicio de sesión', type: 'eCommerce', image: 'projects/stumbaugh/sign-in.jpg' },
    { title: 'Sobre nosotros', type: 'eCommerce', image: 'projects/stumbaugh/about-us.jpg' },
    { title: 'Carrito de compras', type: 'eCommerce', image: 'projects/stumbaugh/cart.jpg' },
    { title: 'Checkout', type: 'eCommerce', image: 'projects/stumbaugh/checkout.jpg' },
    { title: 'Contacto', type: 'eCommerce', image: 'projects/stumbaugh/contact-us.jpg' },
  ]},
  { id: 'c23', name: 'CrediCel', image: 'logos/credicel.png', category: 'Diseño de eCommerce', summary: 'Tienda en línea de celulares y accesorios a crédito. Diseño de eCommerce, realizado mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Listado de celulares', type: 'eCommerce', image: 'projects/credicel/celulares.png' },
    { title: 'Página de inicio', type: 'eCommerce', image: 'projects/credicel/home.png' },
    { title: 'Página de producto', type: 'eCommerce', image: 'projects/credicel/producto.png' },
  ]},
  { id: 'c34', name: 'Centauros de Chihuahua', image: 'logos/centauros-chihuahua.png', category: 'Logotipo & mockup de jersey', summary: 'Equipo de béisbol de Chihuahua. Propuesta de logotipo, isotipo y mockup de jersey.', projects: [
    { title: 'Logotipo completo', type: 'Branding', image: 'projects/centauros/logo-completo.png' },
    { title: 'Mockup de jersey', type: 'Papelería', image: 'projects/centauros/jersey-mockup.png' },
    { title: 'Isotipo "C"', type: 'Branding', image: 'projects/centauros/isotipo-c.png' },
    { title: 'Versión monocolor', type: 'Branding', image: 'projects/centauros/version-monocolor.png' },
  ]},
  { id: 'c33', name: 'JLSV Guaymas-Empalme', image: 'logos/jlsv-guaymas.png', category: 'Propuesta de sitio web', summary: 'Junta Local de Sanidad Vegetal de Guaymas-Empalme. Propuesta de sitio web institucional.', projects: [
    { title: 'Página de inicio', type: 'Diseño web', image: 'projects/jlsv/home.png' },
    { title: 'Nuestros principios', type: 'Diseño web', image: 'projects/jlsv/principios.png' },
    { title: 'Misión y visión', type: 'Diseño web', image: 'projects/jlsv/mision-vision.png' },
    { title: 'Acerca de nosotros', type: 'Diseño web', image: 'projects/jlsv/acerca-de.png' },
    { title: 'Equipo', type: 'Diseño web', image: 'projects/jlsv/equipo.png' },
    { title: 'Ligas de interés', type: 'Diseño web', image: 'projects/jlsv/ligas-interes.png' },
    { title: 'Menú desplegable "Nosotros"', type: 'Diseño web', image: 'projects/jlsv/menu-nosotros.png' },
  ]},
  { id: 'c32', name: 'Isrra Pérez — Entrenador', image: 'logos/isrra-perez.png', category: 'Logotipo, isotipo & variantes', summary: 'Entrenador personal en Ciudad Obregón, Sonora. Diseño de logotipo, isotipo y paleta de color con variantes de aplicación.', projects: [
    { title: 'Logotipo completo', type: 'Branding', image: 'projects/isrra-perez/logo-completo.png' },
    { title: 'Isotipo a color', type: 'Branding', image: 'projects/isrra-perez/isotipo-color.png' },
    { title: 'Isotipo en negro', type: 'Branding', image: 'projects/isrra-perez/isotipo-negro.png' },
    { title: 'Patrón de marca', type: 'Branding', image: 'projects/isrra-perez/patron.png' },
    { title: 'Paleta y variantes', type: 'Branding', image: 'projects/isrra-perez/paleta-variantes.jpg' },
  ]},
  { id: 'c31', name: 'Flowers & Flowers', image: 'logos/flowers-and-flowers.png', category: 'Logotipo, variantes & aplicaciones', summary: 'Florería en El Paso, Texas. Propuesta de logotipo con variantes, paleta de color y aplicaciones (tarjetas, cinta, laptop).', projects: [
    { title: 'Variantes de logotipo', type: 'Branding', image: 'projects/flowers-and-flowers/variantes-logo.png' },
    { title: 'Paleta de color', type: 'Branding', image: 'projects/flowers-and-flowers/paleta-color.png' },
    { title: 'Tarjetas de presentación', type: 'Papelería', image: 'projects/flowers-and-flowers/tarjetas-fondo.jpg' },
    { title: 'Tarjetas — descripción de servicio', type: 'Papelería', image: 'projects/flowers-and-flowers/tarjetas-descripcion.jpg' },
    { title: 'Cinta de empaque', type: 'Papelería', image: 'projects/flowers-and-flowers/cinta.jpg' },
    { title: 'Aplicación en laptop', type: 'Branding', image: 'projects/flowers-and-flowers/laptop.png' },
  ]},
  { id: 'c30', name: 'FG Studio Arquitectura', image: 'logos/fg-studio.png', category: 'Logotipo & papelería', summary: 'Estudio de arquitectura. Diseño de logotipo, tarjetas de presentación y firmas de correo, proyecto por cuenta propia.', projects: [
    { title: 'Perfil de marca', type: 'Branding', image: 'projects/fg-studio/perfil.jpg' },
    { title: 'Membrete', type: 'Papelería', image: 'projects/fg-studio/membrete.jpg' },
    { title: 'Firma de correo — Pedro Florez', type: 'Papelería', image: 'projects/fg-studio/firma-pedro.jpg' },
    { title: 'Firma de correo — Ana Laura González', type: 'Papelería', image: 'projects/fg-studio/firma-ana-laura.jpg' },
  ]},
  { id: 'c29', name: 'Pixelente — Congreso Creativo', image: 'logos/pixelente.png', category: 'Identidad, sitio web & playeras', summary: 'Congreso creativo de diseño gráfico del ITSON Guaymas. Identidad de marca, sitio web y propuesta de playeras.', projects: [
    { title: 'Logotipo', type: 'Branding', image: 'projects/pixelente/wordmark.png' },
    { title: 'Poster del congreso', type: 'Branding', image: 'projects/pixelente/poster.jpg' },
    { title: 'Textura de fondo', type: 'Branding', image: 'projects/pixelente/textura.jpg' },
    { title: 'Propuesta de playeras', type: 'Papelería', image: 'projects/pixelente/playeras-mockup.png' },
    { title: 'Playera gris', type: 'Papelería', image: 'projects/pixelente/playera-gris.png' },
    { title: 'Playera clara', type: 'Papelería', image: 'projects/pixelente/playera-clara.png' },
    { title: 'Pase Full Access', type: 'Sitio web', image: 'projects/pixelente/pase-full-access.png' },
    { title: 'Pase Básico', type: 'Sitio web', image: 'projects/pixelente/pase-basico.png' },
    { title: 'Pase Intermedio', type: 'Sitio web', image: 'projects/pixelente/pase-intermedio.jpg' },
    { title: 'Aparta tu lugar', type: 'Sitio web', image: 'projects/pixelente/pase-info.jpg' },
  ]},
  { id: 'c28', name: 'Brianda Lizárraga', image: 'logos/brianda-lizarraga.png', category: 'Propuesta de sitio web', summary: 'Sitio web de artista musical, con presentaciones, videos, música y redes sociales. Propuesta realizada mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Página de inicio', type: 'Diseño web', image: 'projects/brianda/home.png' },
  ]},
  { id: 'c27', name: 'BP Social Media', image: 'logos/bp-social-media.png', category: 'Logotipo & sitio web', summary: 'Agencia de contenido y comunicación digital. Diseño de logotipo y sitio web, proyecto por cuenta propia.', projects: [
    { title: 'Página de inicio', type: 'Diseño web', image: 'projects/bp-social-media/hero.jpg' },
    { title: 'Nuestro equipo', type: 'Diseño web', image: 'projects/bp-social-media/equipo.jpg' },
    { title: 'Nuestros servicios', type: 'Diseño web', image: 'projects/bp-social-media/servicios.jpg' },
    { title: 'Proyectos', type: 'Diseño web', image: 'projects/bp-social-media/proyectos.jpg' },
    { title: 'Marcas que han confiado en nosotros', type: 'Diseño web', image: 'projects/bp-social-media/marcas.jpg' },
    { title: 'Contacto', type: 'Diseño web', image: 'projects/bp-social-media/contacto.jpg' },
  ]},
  { id: 'c26', name: 'Boba Time', image: 'logos/boba-time.jpg', category: 'Propuesta de redes sociales', summary: 'Tienda de té de burbujas (boba) y postres. Propuesta de contenido para redes sociales, realizada mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Weekend de Boba Time', type: 'Redes sociales', image: 'projects/boba-time/weekend.jpg' },
    { title: 'La mejor tapioca', type: 'Redes sociales', image: 'projects/boba-time/tapioca.jpg' },
    { title: 'Duo perfecto', type: 'Redes sociales', image: 'projects/boba-time/duo-perfecto.jpg' },
    { title: 'Menú — bases de leche', type: 'Redes sociales', image: 'projects/boba-time/menu-base-leche.jpg' },
    { title: 'Menú — bobas', type: 'Redes sociales', image: 'projects/boba-time/menu-bobas.jpg' },
    { title: 'Menú — leche y extras', type: 'Redes sociales', image: 'projects/boba-time/menu-leche-extras.jpg' },
    { title: 'Tamaños y precios', type: 'Redes sociales', image: 'projects/boba-time/tamanos.jpg' },
    { title: 'Mochi', type: 'Redes sociales', image: 'projects/boba-time/mochi.jpg' },
    { title: 'Ordena y recoge', type: 'Redes sociales', image: 'projects/boba-time/ordena-recoge.jpg' },
    { title: "It's Boba Time", type: 'Redes sociales', image: 'projects/boba-time/boba-time-post.jpg' },
  ]},
  { id: 'c25', name: 'B-Clean Service', image: 'logos/bclean.png', category: 'Diseño web', summary: 'Servicio de limpieza de tapicería y detallado automotriz en Mazatlán, Sinaloa. Diseño de sitio web, realizado mientras trabajaba en TICA Solutions (2021-2022).', projects: [
    { title: 'Página de inicio', type: 'Diseño web', image: 'projects/bclean/home.png' },
    { title: 'Resultados profesionales', type: 'Diseño web', image: 'projects/bclean/resultados.png' },
  ]},
  { id: 'c24', name: 'Morena Mujeres', image: 'logos/morena-mujeres.png', category: 'Diseño UI/UX', summary: 'Propuesta de app "Agenda 2022" para Morena Mujeres, diseñada en Adobe XD. Proyecto realizado mientras trabajaba en TICA Solutions (2021-2022), Mazatlán.', projects: [
    { title: 'Inicio de sesión', type: 'UI/UX', image: 'projects/morena/login.jpg' },
    { title: 'Registro de perfil', type: 'UI/UX', image: 'projects/morena/registro.jpg' },
    { title: 'Pantalla de bienvenida', type: 'UI/UX', image: 'projects/morena/home.jpg' },
    { title: 'Splash screen', type: 'UI/UX', image: 'projects/morena/splash.jpg' },
    { title: 'Onboarding editorial', type: 'UI/UX', image: 'projects/morena/onboarding.jpg' },
    { title: 'Calendario', type: 'UI/UX', image: 'projects/morena/calendario.jpg' },
    { title: 'Seguimiento de periodo', type: 'UI/UX', image: 'projects/morena/periodo.jpg' },
    { title: 'Lista de tareas', type: 'UI/UX', image: 'projects/morena/tareas.jpg' },
    { title: 'Control de gastos', type: 'UI/UX', image: 'projects/morena/gastos.jpg' },
    { title: 'Configuración', type: 'UI/UX', image: 'projects/morena/configuracion.jpg' },
  ]},
  { id: 'c43', name: 'Hospital Andalucía', image: 'logos/hospital-andalucia.png', category: 'Diseño editorial', summary: 'Hospital privado en Gómez Palacio y Torreón. Artículos para revista, en colaboración con EXO Films.', projects: [
    { title: 'Artículo — El tiempo es vida: prevenir y tratar el infarto a tiempo', type: 'Revista', image: 'projects/hospital-andalucia/articulo-dr-conrado.jpg' },
    { title: 'Artículo — Prótesis de rodilla', type: 'Revista', image: 'projects/hospital-andalucia/articulo-protesis-rodilla.png' },
  ] },
  { id: 'c42', name: 'Mariscos Beto', image: 'logos/mariscos-beto.png', category: 'Manejo de redes sociales', summary: 'Restaurante de mariscos con sucursales en Mazatlán, Sinaloa y Lerdo, Durango. Manejo de redes sociales y diseño de menú, en colaboración con EXO Films.', projects: [
    { title: 'Post — ¿Se te antojó?', type: 'Redes sociales', image: 'projects/mariscos-beto/se-te-antojo.jpg' },
    { title: 'Post — Nuestras especialidades', type: 'Redes sociales', image: 'projects/mariscos-beto/nuestras-especialidades.jpg' },
    { title: 'Post — El sabor del mar hasta tu casa', type: 'Redes sociales', image: 'projects/mariscos-beto/sabor-del-mar-delivery.jpg' },
    { title: 'Banner — Del mar a tu mesa', type: 'Redes sociales', image: 'projects/mariscos-beto/del-mar-a-tu-mesa.jpg' },
    { title: 'Post — Tu nuevo lugar favorito', type: 'Redes sociales', image: 'projects/mariscos-beto/nuevo-lugar-favorito.jpg' },
    { title: 'Menú — Tostadas, ceviche y cocteles', type: 'Diseño de menú', image: 'projects/mariscos-beto/menu-1.jpg' },
    { title: 'Menú — Palapa de mar', type: 'Diseño de menú', image: 'projects/mariscos-beto/menu-2.jpg' },
    { title: 'Menú — Bebidas', type: 'Diseño de menú', image: 'projects/mariscos-beto/menu-3.jpg' },
    { title: 'Menú — Pa\' los compas', type: 'Diseño de menú', image: 'projects/mariscos-beto/menu-4.jpg' },
    { title: 'Banner — Te esperamos, sucursal Lerdo', type: 'Redes sociales', image: 'projects/mariscos-beto/te-esperamos-lerdo.jpg' },
    { title: 'Post — Testimonios de clientes', type: 'Redes sociales', image: 'projects/mariscos-beto/testimonios.jpg' },
    { title: 'Post — Conoce nuestro Kids Menu', type: 'Redes sociales', image: 'projects/mariscos-beto/kids-menu.jpg' },
    { title: 'Post — Para todos los gustos', type: 'Redes sociales', image: 'projects/mariscos-beto/para-todos-los-gustos.jpg' },
    { title: 'Post — El favorito de la casa', type: 'Redes sociales', image: 'projects/mariscos-beto/el-favorito-de-la-casa.jpg' },
    { title: 'Post — Semana Santa con nosotros', type: 'Redes sociales', image: 'projects/mariscos-beto/semana-santa.jpg' },
  ] },
  { id: 'c41', name: 'Mundo Infantil Laguna', image: 'logos/mundo-infantil.png', category: 'Manejo de redes sociales', summary: 'Salón de fiestas infantiles y ludoteca en Gómez Palacio, Durango. Manejo de redes sociales, en colaboración con EXO Films.', projects: [
    { title: 'Flyer — Posada con nosotros (QR)', type: 'Impreso', image: 'projects/mundo-infantil/flyer-posada-qr.jpg' },
    { title: 'Flyer — Paquetes de fiesta', type: 'Impreso', image: 'projects/mundo-infantil/flyer-paquetes.jpg' },
    { title: 'Flyer — Paquete piñata', type: 'Impreso', image: 'projects/mundo-infantil/flyer-paquete-pinata.jpg' },
    { title: 'Post — Diviértete con tus amigos', type: 'Redes sociales', image: 'projects/mundo-infantil/diviertete-amigos.jpg' },
    { title: 'Post — Agenda abierta, paquetes completos', type: 'Redes sociales', image: 'projects/mundo-infantil/agenda-abierta.jpg' },
    { title: 'Flyer — Posada con nosotros (Santa)', type: 'Impreso', image: 'projects/mundo-infantil/posada-santa.jpg' },
    { title: 'Post — Diversión garantizada', type: 'Redes sociales', image: 'projects/mundo-infantil/diversion-garantizada.jpg' },
    { title: 'Post — Tu fiesta comienza ahora', type: 'Redes sociales', image: 'projects/mundo-infantil/fiesta-comienza-ahora.jpg' },
    { title: 'Post — Diviértete, ríe y celebra con nosotros', type: 'Redes sociales', image: 'projects/mundo-infantil/diviertete-rie-celebra.jpg' },
    { title: 'Banner — Diviértete con tus amigos', type: 'Redes sociales', image: 'projects/mundo-infantil/banner-diviertete-amigos.jpg' },
  ] },
  { id: 'c40', name: 'Bendita Belleza Spa', image: 'logos/bendita-belleza.png', category: 'Manejo de redes sociales', summary: 'Spa y clínica estética en Torreón, Coahuila. Manejo de redes sociales, en colaboración con EXO Films.', projects: [
    { title: 'Post — Atención profesional', type: 'Redes sociales', image: 'projects/bendita-belleza/atencion-profesional.jpg' },
    { title: 'Post — Resultados naturales', type: 'Redes sociales', image: 'projects/bendita-belleza/resultados-naturales.jpg' },
    { title: 'Post — Posada entre amigas', type: 'Redes sociales', image: 'projects/bendita-belleza/posada-entre-amigas.jpg' },
    { title: 'Post — Lista para brillar esta navidad', type: 'Redes sociales', image: 'projects/bendita-belleza/brillar-navidad.jpg' },
    { title: 'Post — Recibe el año nuevo con tu mejor versión', type: 'Redes sociales', image: 'projects/bendita-belleza/ano-nuevo-mejor-version.jpg' },
    { title: 'Post — No olvides cuidar de ti', type: 'Redes sociales', image: 'projects/bendita-belleza/cuidar-de-ti.jpg' },
    { title: 'Post — Exosomas capilares', type: 'Redes sociales', image: 'projects/bendita-belleza/exosomas-capilares.jpg' },
    { title: 'Flyer — Aniversario Expo 2025', type: 'Impreso', image: 'projects/bendita-belleza/expo-2025.jpg' },
    { title: 'Post — Tratamiento con Dermapen', type: 'Redes sociales', image: 'projects/bendita-belleza/dermapen.jpg' },
    { title: 'Post — Tratamiento con Lipoenzimas', type: 'Redes sociales', image: 'projects/bendita-belleza/lipoensimas.jpg' },
    { title: 'Post — Promoción Buen Fin, terapia facial Dermapen', type: 'Redes sociales', image: 'projects/bendita-belleza/buen-fin-dermapen.jpg' },
    { title: 'Post — Promoción Buen Fin, depilación láser', type: 'Redes sociales', image: 'projects/bendita-belleza/buen-fin-depilacion-laser.jpg' },
  ] },
  { id: 'c39', name: 'EnsuringLives', image: 'logos/ensuring-lives.png', category: 'Manejo de redes sociales', website: 'ensuringlives.mx', summary: 'Aseguradora de vidas y planes de protección. Manejo de redes sociales, en colaboración con EXO Films.', projects: [
    { title: 'Post — Tu salud no debería tener límites', type: 'Redes sociales', image: 'projects/ensuring-lives/tu-salud-sin-limites.jpg' },
    { title: 'Post — Si mañana faltaras, ¿tu familia estaría preparada?', type: 'Redes sociales', image: 'projects/ensuring-lives/si-manana-faltaras.jpg' },
    { title: 'Post — ¿Tu dinero no está creciendo?', type: 'Redes sociales', image: 'projects/ensuring-lives/tu-dinero-no-crece.jpg' },
    { title: 'Post — Una hospitalización puede borrar años de ahorro', type: 'Redes sociales', image: 'projects/ensuring-lives/hospitalizacion-ahorro.jpg' },
    { title: 'Post — Con el tiempo, los riesgos aumentan', type: 'Redes sociales', image: 'projects/ensuring-lives/riesgos-aumentan.jpg' },
    { title: 'Post — Ignorar tu futuro también es una decisión', type: 'Redes sociales', image: 'projects/ensuring-lives/ignorar-tu-futuro.jpg' },
    { title: 'Post — Un accidente fuera del país', type: 'Redes sociales', image: 'projects/ensuring-lives/accidente-fuera-del-pais.jpg' },
    { title: 'Post — Si hoy faltaras, ¿tu familia estaría protegida?', type: 'Redes sociales', image: 'projects/ensuring-lives/si-hoy-faltaras.jpg' },
  ] },
  { id: 'c38', name: 'Clínica Dental Andalucía', image: 'logos/clinica-andalucia.png', category: 'Manejo de redes sociales', summary: 'Clínica dental con sucursales en Coahuila y Durango. Manejo de redes sociales, en colaboración con EXO Films.', projects: [
    { title: 'Flyer — Apertura sucursal Círculo Salud', type: 'Impreso', image: 'projects/clinica-andalucia/flyer-apertura-circulo-salud.jpg' },
    { title: 'Post — Su primer visita al dentista', type: 'Redes sociales', image: 'projects/clinica-andalucia/primera-visita-dentista.png' },
    { title: 'Post — Sonríe siempre, 3 resinas x $1,500', type: 'Redes sociales', image: 'projects/clinica-andalucia/resinas-promo-oct-1.jpg' },
    { title: 'Post — Limpieza dental 2x1', type: 'Redes sociales', image: 'projects/clinica-andalucia/limpieza-2x1-oct-2.jpg' },
    { title: 'Post — San Valentín', type: 'Redes sociales', image: 'projects/clinica-andalucia/san-valentin.jpeg' },
    { title: 'Post — Transformamos sonrisas', type: 'Redes sociales', image: 'projects/clinica-andalucia/transformamos-sonrisas-1.jpg' },
    { title: 'Post — Nuestros servicios', type: 'Redes sociales', image: 'projects/clinica-andalucia/nuestros-servicios.jpg' },
    { title: 'Post — Comprometidos con tu bienestar', type: 'Redes sociales', image: 'projects/clinica-andalucia/comprometidos-bienestar.jpg' },
    { title: 'Post — Día mundial contra el cáncer de mama', type: 'Redes sociales', image: 'projects/clinica-andalucia/dia-cancer-mama.jpg' },
    { title: 'Post — Urgencia de última hora en fin de semana', type: 'Redes sociales', image: 'projects/clinica-andalucia/urgencia-fin-semana.jpg' },
    { title: 'Post — Transformamos sonrisas (ortodoncia)', type: 'Redes sociales', image: 'projects/clinica-andalucia/transformamos-sonrisas-2.jpg' },
  ] },
  { id: 'c37', name: 'Black & White Studio', image: 'logos/black-and-white-studio.png', category: 'Identidad, diseño web & papelería', website: 'bnwstudio.xyz', summary: 'Mi propio estudio de marketing y consultoría. Identidad de marca completa, diseño web, papelería y contenido de redes sociales.', projects: [
    { title: 'Papelería — tarjeta de presentación', type: 'Papelería', image: 'projects/black-and-white-studio/tarjeta-presentacion.png' },
    { title: 'Mockup — sitio web', type: 'Diseño web', image: 'projects/black-and-white-studio/mockup-sitio-web.jpg' },
    { title: 'Post — ¿Tu sitio web necesita un refresh?', type: 'Redes sociales', image: 'projects/black-and-white-studio/refresh-sitio-web.jpg' },
    { title: 'Post — Branding & redes sociales', type: 'Redes sociales', image: 'projects/black-and-white-studio/branding-redes-sociales.jpg' },
    { title: 'Post — Mejoremos el SEO de tu web', type: 'Redes sociales', image: 'projects/black-and-white-studio/seo-de-tu-web.jpg' },
    { title: 'Post — Servicios de consultoría', type: 'Redes sociales', image: 'projects/black-and-white-studio/servicios-consultoria.jpg' },
    { title: 'Post — ¿Qué necesita tu negocio?', type: 'Redes sociales', image: 'projects/black-and-white-studio/que-necesita-tu-negocio.jpg' },
    { title: 'Post — Marketing vs Publicidad', type: 'Redes sociales', image: 'projects/black-and-white-studio/marketing-vs-publicidad.jpg' },
  ] },
  { id: 'c36', name: 'AgroByte', image: 'logos/agrobyte.png', category: 'Identidad & redes sociales', summary: 'Marca hermana de Byte Drone Center enfocada en drones agrícolas (DJI Agras). Manejo de redes sociales, diseño de flyers y cobertura de evento de demostración.', projects: [
    { title: 'Flyer — Demo DJI Agras T40 (español)', type: 'Redes sociales', image: 'projects/agrobyte/flyer-demo-t40-es.png' },
    { title: 'Flyer — Demo DJI Agras T40 (inglés)', type: 'Redes sociales', image: 'projects/agrobyte/flyer-demo-t40-eng.png' },
    { title: 'Post — Cómo se usan los drones en la agricultura', type: 'Redes sociales', image: 'projects/agrobyte/post-agriculture-1.jpg' },
    { title: 'Post — Los drones pueden revolucionar la agricultura', type: 'Redes sociales', image: 'projects/agrobyte/post-agriculture-2.jpg' },
    { title: 'Post — Comparativa DJI Agras T20P vs T40', type: 'Redes sociales', image: 'projects/agrobyte/comparativa-t20p-t40.jpg' },
    { title: 'Post — Bundle DJI Agras T40', type: 'Redes sociales', image: 'projects/agrobyte/bundle-t40.png' },
    { title: 'Post — Desata el potencial de tus campos', type: 'Redes sociales', image: 'projects/agrobyte/unleash-potential.png' },
    { title: 'Post — Detalle de control remoto', type: 'Redes sociales', image: 'projects/agrobyte/remote-control-detail.png' },
    { title: 'Post — Aspersión y mapeo simultáneo', type: 'Redes sociales', image: 'projects/agrobyte/spraying-mapping.png' },
    { title: 'Portada de Facebook', type: 'Redes sociales', image: 'projects/agrobyte/portada-fb.png' },
    { title: 'Post fijo — DJI Agras T40', type: 'Redes sociales', image: 'projects/agrobyte/post-fijo-t40.png' },
    { title: 'Cobertura de evento — Demo Julio 2023', type: 'Fotografía', image: 'projects/agrobyte/demo-julio-2023.jpg' },
    { title: 'Cobertura de evento — Rancho Santa Margarita', type: 'Fotografía', image: 'projects/agrobyte/collage-evento-1.jpg' },
    { title: 'Cobertura de evento — Stand y banderas', type: 'Fotografía', image: 'projects/agrobyte/collage-evento-2.jpg' },
  ] },
  { id: 'c35', name: 'Byte Drone Center', image: 'logos/byte-drone-center.png', category: 'Redes sociales, edición de video & identidad', summary: 'Centro de drones en San Carlos, Sonora. Manejo de redes sociales, edición de video y gestión general de identidad de marca.', projects: [
    { title: 'Flyer — Bienvenido al mundo de los drones', type: 'Impreso', image: 'projects/byte-drone-center/flyer-espanol.png' },
    { title: 'Story — Curso Arma tu Drone', type: 'Redes sociales', image: 'projects/byte-drone-center/story-courses.png' },
    { title: 'Carrusel — Curso Introducción Básica', type: 'Redes sociales', image: 'projects/byte-drone-center/basic-intro-course-wide.png' },
    { title: 'Post — Curso Introducción Básica', type: 'Redes sociales', image: 'projects/byte-drone-center/basic-intro-course-square.jpg' },
    { title: 'Post — Curso Arma tu Drone', type: 'Redes sociales', image: 'projects/byte-drone-center/build-drone-course-post.jpg' },
    { title: 'Post — Curso de Mapeo con Drone', type: 'Redes sociales', image: 'projects/byte-drone-center/drone-mapping-course.png' },
    { title: 'Post — DJI Mavic Series', type: 'Redes sociales', image: 'projects/byte-drone-center/mavic-series-post.jpg' },
    { title: 'Post — Familia Mavic', type: 'Redes sociales', image: 'projects/byte-drone-center/mavic-family.png' },
    { title: 'Post — Mavic 3 Multiespectral / AgroByte', type: 'Redes sociales', image: 'projects/byte-drone-center/mavic3-multispectral.png' },
    { title: 'Post — El drone que se ajusta a ti', type: 'Redes sociales', image: 'projects/byte-drone-center/drone-que-fits.jpg' },
    { title: 'Post — DJI Mini 3', type: 'Redes sociales', image: 'projects/byte-drone-center/mini3.png' },
    { title: 'Post — Aprende con Tello', type: 'Redes sociales', image: 'projects/byte-drone-center/tello.png' },
    { title: 'Collage de productos', type: 'Redes sociales', image: 'projects/byte-drone-center/collage-productos.jpg' },
  ] },
];

const SKILLS = ['Branding & identidad', 'UI/UX', 'Marketing digital', 'Redes sociales', 'Adobe Creative Cloud', 'Figma', 'WordPress', 'Fotografía creativa'];

const EXPERIENCE = [
  { period: '2020 — hoy', role: 'Docente por Asignatura', org: 'Instituto Tecnológico de Sonora', detail: 'Clases en Diseño Gráfico, Mercadotecnia e Inglés (hasta B1); planeación didáctica y evaluación por competencias.' },
  { period: '2021 — 2022', role: 'Diseñadora UI/UX', org: 'TICA Solutions', detail: 'Interfaces web y móviles en Figma y Adobe XD; identidad corporativa, manuales de marca y contenido para redes.' },
  { period: '2019 — 2021', role: 'Encargada de Marketing', org: 'ECO Fumigaciones', detail: 'Redes sociales y campañas de publicidad digital; supervisión de sucursal y desarrollo de identidad visual.' },
];

const EDUCATION = [
  { period: '2024 — 2026', title: 'Maestría en Comunicación Corporativa + Design Management', org: 'Universidad Internacional de La Rioja (UNIR), CDMX' },
  { period: '2012 — 2016', title: 'Licenciatura en Diseño Gráfico', org: 'Universidad de Sonora, Hermosillo' },
];

const CERTIFICATIONS = ['Diploma en Identidad y Branding', 'Diploma en Comunicación Estratégica', 'Diploma en Investigación e Innovación en Comunicación y Marca', 'Diplomado en Soft Skills y Habilidades Directivas'];

const ALL_COURSES = [
  { title: 'Claude 101', hours: 2 },
  { title: 'El ecosistema de la impresión 3D: Hardware, software y materiales', hours: 20 },
  { title: 'AI Fundamentals', hours: 2 },
  { title: 'Certifying Adobe Skills in Your Classroom', hours: 6 },
  { title: 'New Technologies for Business Leaders', hours: 19 },
  { title: 'AI, Empathy & Ethics', hours: 4 },
  { title: 'Introducción a la ingeniería en Inteligencia Artificial', hours: 2 },
  { title: 'Introducción a la IA generativa', hours: 1 },
  { title: 'Continuing Education Certificate in Design Management', hours: 160 },
  { title: 'Introducción a Google Analytics 4', hours: 1 },
  { title: 'Especialización en Marketing Digital con Inteligencia Artificial', hours: 54 },
  { title: 'Segmentación de clientes', hours: 2 },
  { title: 'Plan de Marketing Digital', hours: 4 },
  { title: 'Inbound Marketing para el E-Commerce', hours: 2 },
  { title: 'Ecommerce', hours: 4 },
  { title: 'Content Marketing', hours: 2 },
  { title: 'Creación de contenido digital con Inteligencia Artificial', hours: 2 },
  { title: 'Fundamentos y Aplicaciones de la Inteligencia Artificial', hours: 2 },
  { title: 'Marketing Digital con Inteligencia Artificial', hours: 2 },
  { title: 'Diseño Gráfico con Inteligencia Artificial', hours: 2 },
  { title: 'Community Management', hours: 2 },
  { title: 'Innovación empresarial', hours: 6 },
  { title: 'Big Data y Monetización', hours: 2 },
  { title: 'Especialización en Transformación Digital', hours: 24 },
  { title: 'Desarrolla aptitudes para la IA en tu organización como líder', hours: 1 },
  { title: 'Integración de la IA generativa en la estrategia empresarial', hours: 1 },
  { title: 'Retos y oportunidades de la IA para el liderazgo', hours: 1 },
  { title: 'Introducción al Deep Learning', hours: 1 },
  { title: 'Introducción a Web Scraping', hours: 1 },
  { title: 'Mantiene a tu equipo a la vanguardia de la innovación en IA', hours: 1 },
  { title: 'Introducción a Machine Learning', hours: 1 },
  { title: 'IA generativa para líderes empresariales', hours: 1 },
  { title: 'Tendencias y tecnologías disruptivas', hours: 1 },
  { title: 'Taller Figma', hours: 1 },
  { title: 'Buenas prácticas UX', hours: 1 },
  { title: 'Neuromarketing', hours: 15 },
  { title: 'Google: Inteligencia Artificial y productividad', hours: 8 },
  { title: 'Marketing emocional: el lado humano de las marcas', hours: 1 },
  { title: 'Optimización On Page y Off Page', hours: 1 },
  { title: 'SEO Avanzado', hours: 2 },
  { title: 'Monetiza tu proyecto web con SEO', hours: 1 },
  { title: 'Potencia tu sitio web con SEO', hours: 1 },
  { title: 'Reforma Laboral', hours: 2 },
  { title: 'Fundamentos del content marketing: Blogs', hours: 2 },
  { title: 'Adobe XD CC: Master diseño profesional de prototipos', hours: 22 },
  { title: 'Design Thinking: Experiencia del cliente', hours: 1 },
  { title: 'Teaching with Purpose', hours: 30 },
  { title: 'Diseño Instruccional a través de IA basado en el EC0301', hours: 10 },
  { title: 'Evaluación por competencias e instrumentos de evaluación', hours: 2 },
  { title: 'Entrenamiento para educador Google Nivel 1', hours: 6 },
  { title: 'Programa avanzado de formación de instructores 360 grados', hours: 10 },
  { title: 'Mindfulness & Worklife Balance', hours: 8 },
  { title: 'Educación superior y docencia universitaria', hours: 9 },
];

const LANGUAGES = [
  { name: 'Español', level: 'Nativo' },
  { name: 'Inglés', level: 'Intermedio alto (B2)' },
];

const SOFT_SKILLS = ['Creatividad e innovación', 'Resolución de problemas', 'Comunicación efectiva', 'Trabajo en equipo', 'Gestión de proyectos'];

const SERVICES = ['Identidad corporativa y branding', 'Diseño web CMS y WordPress', 'Manejo de redes sociales', 'Community management', 'Fotografía creativa y de producto', 'Publicidad digital e impresa', 'Posicionamiento web'];

const BIO = 'Diseñadora gráfica, consultora y docente con más de 10 años de experiencia impulsando marcas a través de la estrategia, el diseño y la comunicación digital. Mi enfoque principal es la consultoría para negocios y empresas que buscan fortalecer su identidad, optimizar su presencia digital y desarrollar una comunicación efectiva. Especializada en branding, marketing digital, gestión de redes sociales y desarrollo de sitios web, complemento cada proyecto con experiencia en diseño de interfaces (UI/UX), identidad visual y herramientas como Adobe Creative Cloud, Figma y WordPress. Además, cuento con 6 años de experiencia como docente en Diseño Gráfico y Mercadotecnia, formando nuevos profesionales y manteniéndome en constante evolución dentro de la industria. Black and White Studio es el espacio donde convergen estrategia, consultoría y diseño para crear soluciones que generan valor, fortalecen marcas y conectan con las personas.';
